apiVersion: apps/v1
kind: Deployment
metadata:
  name: khugu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khugu
  template:
    metadata:
      labels:
        app: khugu
    spec:
      containers:
      - image: okteto.dev/khugu:latest
        name: khugu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d8c4d1d4-ad12-4f0f-848c-c0bf60308d11"
        - name: Vless_Path
          value: "/vl555jtyjj"
        - name: Vmess_UUID
          value: "d8c4d1d4-ad12-4f0f-848c-c0bf60308d11"
        - name: Vmess_Path
          value: "/vm66vgdg6"
        - name: Share_Path
          value: "/v2link"
